[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

# Deploy previews for all branches (including staging)
[build.environment]
  NODE_VERSION = "20"

[context.production]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
